swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Digital Credentials"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "seba-dcc.github.io"
basePath: "/swagger-ui/"
tags:
- name: "First Application"
  description: "To be defined"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "Second Application"
  description: "To be defined"
  externalDocs:
    description: ""
    url: "http://swagger.io"
schemes:
- "https"
paths:
  /create-did:
    post:
      tags:
      - "First Application"
      summary: "Create DID for university"
      description: "To be defined"
      operationId: "createDid"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request with Did-ID"
        required: true
        schema:
          $ref: "#/definitions/DidRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/DidResponse"
        500:
          description: "internal server error"
  /create-credential:
    post:
      tags:
      - "First Application"
      summary: "Create credential"
      description: ""
      operationId: "createCredential"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request with all ids of the credentials needed"
        required: true
        schema:
          type: array
          items: 
            $ref: "#/definitions/CredentialRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
               $ref: '#/definitions/VerifiableCredential'
        500:
          description: "internal server error"
  /offered-credentials:
    get:
      tags:
      - "First Application"
      summary: "Credentials that TUM can issue for the student"
      description: ""
      operationId: "offeredCredentials"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student number"
        required: true
        schema:
          $ref: "#/definitions/CredentialOfferedRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CredentialsResponse"
        500:
          description: "internal server error"
  /signed-credential:
    get:
      tags:
      - "First Application"
      summary: "Get already created credential"
      description: ""
      operationId: "signedCredential"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Id of the credential"
        required: true
        schema:
          $ref: "#/definitions/CredentialId"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/VerifiableCredential"
        500:
          description: "internal server error"
  /verify-credential:
    get:
      tags:
      - "Second Application"
      summary: "Verify a VC"
      description: ""
      operationId: "verifyCredential"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "VC that needs to be verified"
        required: true
        schema:
          $ref: "#/definitions/VerifiableCredential"
      responses:
        200:
          description: "successful operation"
          schema:
             type: "object"
             properties:
               verified:
                   type: "boolean"
        500:
          description: "internal server error"
definitions:
  VerifiableCredential:
    type: "object"
    properties:
      id:
        type: "string"
      context:
        type: "string"
      type:
        type: "string"
      issuer:
        type: "string"
      issuanceDate:
        type: "string"
      credentialSubject:
        type: "string"
      proof:
        type: "string"
    xml:
      name: "VerifiableCredential"
  DidResponse:
    type: "object"
    properties:
      id:
        type: "string"
      address:
        type: "string"
    xml:
      name: "DidResponse"
  DidRequest:
    type: "object"
    properties:
      tls-key:
        type: "string"
    xml:
      name: "DidRequest"
  CredentialRequest:
    type: "object"
    properties:
      credential-subject:
          type: "string"
      credential-id:
          type: "string"
    xml:
      name: "CredentialRequest"
  CredentialOfferedRequest:
    type: "object"
    properties:
      mat-num:
        type: "string"
    xml:
      name: "CredentialOfferedRequest"
  CredentialsResponse:
    type: "object"
    properties:
      credential-ids:
        type: "array"
        items:
          type: "string"
    xml:
      name: "CredentialsResponse"
  CredentialId:
    type: "object"
    properties:
      credential-id:
          type: "string"
    xml:
      name: "CredentialId"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"