swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Digital Credentials"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "seba-dcc.github.io"
basePath: "/swagger-ui/"
tags:
  - name: "TUM Signing Server / Issuer API"
  - name: "Verifier API"
schemes:
  - "https"
paths:
  /create-did:
    post:
      tags:
        - "TUM Signing Server / Issuer API"
      summary: "Create DID for university / institutes"
      description: "To be defined"
      operationId: "createDid"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Request with Did-ID"
          required: true
          schema:
            $ref: "#/definitions/DidRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/DidResponse"
        204:
          description: "Domain already exists"
        500:
          description: "internal server error"
  /create-credential:
    post:
      tags:
        - "TUM Signing Server / Issuer API"
      summary: "Create credential"
      description: ""
      operationId: "createCredential"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Request with all ids of the credentials needed"
          required: true
          schema:
            $ref: "#/definitions/CredentialRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/VerifiableCredential"
        500:
          description: "internal server error"
  /offered-credentials:
    get:
      tags:
        - "TUM Signing Server / Issuer API"
      summary: "Credentials that TUM can issue for the student"
      description: ""
      operationId: "offeredCredentials"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Student number"
          required: true
          schema:
            $ref: "#/definitions/CredentialOfferedRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CredentialsResponse"
        500:
          description: "internal server error"
  /signed-credential:
    get:
      tags:
        - "TUM Signing Server / Issuer API"
      summary: "Get already created credential"
      description: ""
      operationId: "signedCredential"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Id of the credential"
          required: true
          schema:
            $ref: "#/definitions/CredentialId"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/VerifiableCredential"
        500:
          description: "internal server error"
  /verify-credential:
    post:
      tags:
        - "Verifier API"
      summary: "Verify a VC"
      description: ""
      operationId: "verifyCredential"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - in: "formData"
          name: "vc"
          type: "file"
          description: "VC that needs to be verified"
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              verified:
                type: "boolean"
        500:
          description: "internal server error"
          schema:
            $ref: "#/definitions/verifyCredentialError"
definitions:
  VerifiableCredential:
    type: "object"
    properties:
      id:
        type: "string"
        example: "https://example.com/credentials/1872"
      context:
        type: "array"
        items:
          type: "string"
        example:
          - "https://www.w3.org/2018/credentials/v1"
          - "https://www.w3.org/2018/credentials/examples/v1"
      type:
        type: "array"
        items:
          type: "string"
        example:
          - "VerifiableCredential"
          - "DegreeCredential"
      issuer:
        type: "string"
        example: "did:tls:tum.de"
      issuanceDate:
        type: "string"
        example: "2010-01-01T19:23:24Z"
      credentialSubject:
        type: "object"
        example: {
          "did": "eth:did:sdhed545l",
          "alumniOf": "Technische Universit채t M체nchen",
          "grade": "1,0",
          "degreeType": "bachelor"
        }
      proof:
        type: "object"
        example:
          - type: Ed25519Signature2018
            created: '2020-12-15T11:07:10Z'
            jws: eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..kSp-z5 -cU3mxdJUJaDX_5xOHGF66nd2X9wdAisKMNH1OIlueXcKjO6TFDKrNHa3PIyRZMaTQ6TtZgIQ0mx7YAg
            proofPurpose: assertionMethod
            verificationMethod: 'did:tum'
    xml:
      name: "VerifiableCredential"
  verifyCredentialError:
    type: "object"
    properties:
      valid:
        type: "boolean"
        example: false
      error:
        type: "string"
        example: "Proof Missing in the Credential"
  DidResponse:
    type: "object"
    properties:
      id:
        type: "string"
      address:
        type: "string"
      didDocument:
        type: "object"
        properties:
          "@context":
            type: "string"
          id:
            type: "string"
          service:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "string"
                type:
                  type: "string"
                serviceEndpoint:
                  type: "string"
          assertionMethod:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "string"
                type:
                  type: "string"
                controller:
                  type: "string"
                publicKeyBase58:
                  type: "string"
    example:
      id: "did:tls:tum.de"
      address: "0x492140a461075F183556A6C9f718DF6e4df2f977"
      didDocument:
        "@context": "https://www.w3.org/ns/did/v1"
        id: "did:tls:tum.de"
        service:
          - id: "did:tls:tum.de#vcs"
            type: "VerifiableCredentialService"
            serviceEndpoint: "http://localhost:9004"
        assertionMethod:
          - id: "did:tls:tum.de#keys-1"
            type: "Ed25519VerificationKey2018"
            controller: "did:tls:tum.de"
            publicKeyBase58: "E4tGev3GUgzsXZ6sJpSa259Y16gmW6zpNHESTtJGvVCb"
    xml:
      name: "DidResponse"
  DidRequest:
    type: "object"
    properties:
      domain:
        type: "string"
        example: "tum.de"
    xml:
      name: "DidRequest"
  CredentialRequest:
    type: "object"
    properties:
      domain:
        type: "string"
        example: "tum.de"
      requestedCredentials:
        type: "array"
        items:
          type: "object"
          properties:
            credentialType:
              type: "string"
              example: "degree"
            credentialSubject:
              type: "object"
              properties:
                did:
                  type: "string"
                  example: "eth:did:sdhed545l"
                alumniOf:
                  type: "string"
                  example: "Technische Universit채t M체nchen"
                grade:
                  type: "number"
                  example: 1,0
                degreeType:
                  type: "string"
                  example: "bachelor"
    xml:
      name: "CredentialRequest"
  CredentialOfferedRequest:
    type: "object"
    properties:
      matNum:
        type: "string"
    xml:
      name: "CredentialOfferedRequest"
  CredentialsResponse:
    type: "object"
    properties:
      credentialTypes:
        type: "array"
        items:
          type: "string"
    xml:
      name: "CredentialsResponse"
  CredentialId:
    type: "object"
    properties:
      credential-id:
        type: "string"
    xml:
      name: "CredentialId"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
